# Generated by Django 4.2 on 2023-05-10 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='City')),
                ('image', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Map')),
                ('mapsURL', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Maps link')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.URLField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Country')),
                ('image', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Map')),
                ('mapsURL', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Maps link')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.continent')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.continent'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.country'),
        ),
    ]
