# Generated by Django 4.2 on 2023-05-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
